[chore][exporter/awsxrayexporter] improve linting (#44894)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

This is part of the process to enable the
[modernize](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44199)
linter in CI and upgrade `golanglint` to the latest version.

There are no changes in the component behaviour.

```sh
Error: exporter/awsxrayexporter/internal/translator/segment.go:579:9: G602: slice index out of range (gosec)
	content[0] = '1'
	       ^
Error: exporter/awsxrayexporter/internal/translator/segment.go:580:9: G602: slice index out of range (gosec)
	content[1] = '-'
	       ^
Error: exporter/awsxrayexporter/internal/translator/segment.go:582:9: G602: slice index out of range (gosec)
	content[10] = '-'
	       ^
```

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>