[chore][ci] Fix actionlint CI and enable actionlint on Windows workflows (#50438)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

Actionlint CI was not working due to a dependency break. See
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/32523439046/job/96900423695?pr=50438

```sh
Run make actionlint
  make actionlint
  shell: /usr/bin/bash -e {0}
  env:
    BASELINE_SPACE: 99366
    GOTOOLCHAIN: local
# github.com/rhysd/actionlint
Error: ../../../go/pkg/mod/github.com/rhysd/actionlint@v1.7.12/action_metadata.go:273:22: te.Errors[0].Error undefined (type string has no field or method Error)
Error: ../../../go/pkg/mod/github.com/rhysd/actionlint@v1.7.12/parse.go:1555:59: e.Err undefined (type string has no field or method Err)
Error: ../../../go/pkg/mod/github.com/rhysd/actionlint@v1.7.12/parse.go:1556:16: e.Line undefined (type string has no field or method Line)
Error: ../../../go/pkg/mod/github.com/rhysd/actionlint@v1.7.12/parse.go:1557:16: e.Column undefined (type string has no field or method Column)
Error: ../../../go/pkg/mod/github.com/rhysd/actionlint@v1.7.12/parse.go:1567:26: undefined: yaml.ParserError
config-file .github/actionlint.yaml -color .github/workflows/add-codeowners-to-pr.yml .github/workflows/add-labels.yml .github/workflows/approve-workflows.yml .github/workflows/build-and-test-arm.yml .github/workflows/build-and-test-darwin.yaml .github/workflows/build-and-test-windows.yml .github/workflows/build-and-test.yml .github/workflows/changelog.yml .github/workflows/check-codeowners.yaml .github/workflows/check-links.yaml .github/workflows/check-lychee-config.yml .github/workflows/check-merge-freeze.yml .github/workflows/close-stale.yaml .github/workflows/codeql-analysis.yml .github/workflows/e2e-tests-windows.yml .github/workflows/e2e-tests.yml .github/workflows/first-time-contributor.yml .github/workflows/fossa.yml .github/workflows/generate-codeowners-activity.yml .github/workflows/generate-component-labels.yml .github/workflows/generate-pr-from-changelog.yml .github/workflows/generate-weekly-report.yml .github/workflows/golden.yml .github/workflows/lint-workflow-files.yml .github/workflows/load-tests.yml .github/workflows/mark-issues-as-stale.yml .github/workflows/milestone-add-to-pr.yml .github/workflows/ping-codeowners-issues.yml .github/workflows/ping-codeowners-on-new-issue.yml .github/workflows/ping-codeowners-prs.yml .github/workflows/prepare-release.yml .github/workflows/prometheus-compliance-tests.yml .github/workflows/rerun-workflows.yml .github/workflows/scoped-test.yaml .github/workflows/scorecard.yml .github/workflows/shellcheck.yaml .github/workflows/survey-on-merged-pr.yml .github/workflows/telemetrygen.yml .github/workflows/tidy-dependencies.yml .github/workflows/update-otel.yaml .github/workflows/zizmor.yml
bash: line 1: config-file: command not found
make: [Makefile:719: actionlint] Error 127 (ignored)
```

Previously was also skipping the Windows actions files, this PR
re-enables it.

Also fixing all the actionlint errors:

```sh
.github/workflows/load-tests.yml:87:9: shellcheck reported issue in this script: SC2001:style:1:14: See if you can use ${variable//search/replace} instead [shellcheck]
   |
87 |         run: echo "name=$(echo "${MATRIX_TEST}" | sed -e 's/|/_/g')" >> "$GITHUB_OUTPUT"
   |         ^~~~
.github/workflows/build-and-test-windows.yml:104:9: shellcheck reported issue in this script: SC1070:error:1:1: Parsing stopped here. Mismatched keywords or invalid parentheses? [shellcheck]
    |
104 |         run: |
    |         ^~~~
.github/workflows/build-and-test-windows.yml:104:9: shellcheck reported issue in this script: SC1133:error:1:1: Unexpected start of line. If breaking lines, |/||/&& should be at the end of the previous one [shellcheck]
    |
104 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:103:9: shellcheck reported issue in this script: SC1070:error:1:1: Parsing stopped here. Mismatched keywords or invalid parentheses? [shellcheck]
    |
103 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:103:9: shellcheck reported issue in this script: SC1133:error:1:1: Unexpected start of line. If breaking lines, |/||/&& should be at the end of the previous one [shellcheck]
    |
103 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:113:9: shellcheck reported issue in this script: SC1009:info:1:117: The mentioned syntax error was in this simple command [shellcheck]
    |
113 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:113:9: shellcheck reported issue in this script: SC1009:info:1:77: The mentioned syntax error was in this simple command [shellcheck]
    |
113 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:113:9: shellcheck reported issue in this script: SC1072:error:1:104: Expected end of double quoted string. Fix any mentioned problems and try again [shellcheck]
    |
113 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:113:9: shellcheck reported issue in this script: SC1072:error:1:208: Expected end of double quoted string. Fix any mentioned problems and try again [shellcheck]
    |
113 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:113:9: shellcheck reported issue in this script: SC1073:error:1:117: Couldn't parse this double quoted string. Fix to allow more checks [shellcheck]
    |
113 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:113:9: shellcheck reported issue in this script: SC1073:error:1:77: Couldn't parse this double quoted string. Fix to allow more checks [shellcheck]
    |
113 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:122:9: shellcheck reported issue in this script: SC1001:info:2:18: This \S will be a regular 'S' in this context [shellcheck]
    |
122 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:122:9: shellcheck reported issue in this script: SC1001:info:2:25: This \C will be a regular 'C' in this context [shellcheck]
    |
122 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:122:9: shellcheck reported issue in this script: SC1001:info:2:43: This \S will be a regular 'S' in this context [shellcheck]
    |
122 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:122:9: shellcheck reported issue in this script: SC1001:info:2:52: This \E will be a regular 'E' in this context [shellcheck]
    |
122 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:122:9: shellcheck reported issue in this script: SC1001:info:2:61: This \A will be a regular 'A' in this context [shellcheck]
    |
122 |         run: |
    |         ^~~~
.github/workflows/e2e-tests-windows.yml:122:9: shellcheck reported issue in this script: SC1001:info:2:73: This \o will be a regular 'o' in this context [shellcheck]
    |
122 |         run: |
    |         ^~~~
make: *** [actionlint] Error 1
```

Relates to
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/51106

<!--Authorship attestation. See AGENTS.md for details. AI agents must
not check this box on behalf
of the user; the human author must check it themselves before the PR is
ready for review.-->
#### Authorship

- [x] I, a human, wrote this pull request description myself.

<!--Please delete paragraphs that you did not use before submitting.-->

---------

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>