Improve OTTL error message (#31233)
**Description:**
Improve OTTL context error messages when an unknown path is used.

The new error message will look like:

```
Error: invalid configuration: processors::transform: unable to parse OTTL statement "set(attributes[\"test\"], trace_id.hex)": error while parsing arguments for call to "set": invalid argument at position 1: trace_id.hex is not a valid path for the Span context - review https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottlspan to see all valid paths
```

**Link to tracking Issue:** <Issue number if applicable>

Related to
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29871
Closes
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29922

**Testing:** <Describe what testing was performed and which tests were
added.>

Unit tests

---------

Co-authored-by: Evan Bradley <11745660+evan-bradley@users.noreply.github.com>