[chore][receiver/activedirectorydsreceiver] run make modernize (#44669)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

Run the `make modernize` tool.

https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize

This is part of the process to enable the
[modernize](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44199)
linter in CI.

There are no changes in the component behaviour.

```sh
Error: receiver/activedirectorydsreceiver/counters_test.go:55:2: slicescontains: Loop can be simplified using slices.Contains (modernize)
	for _, availableCounter := range m.availableCounterNames {
	^
make[2]: *** [../../Makefile.Common:282: lint] Error 1
make[1]: *** [Makefile:254: receiver/activedirectorydsreceiver] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>