[chore][receiver/windowseventlogreceiver] improve linting (#44224)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

This is part of the process to enable the
[modernize](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44199)
linter in CI and upgrade `golanglint` to the latest version.

There are no changes in the component behaviour.

```sh
WARN [runner/exclusion_paths] The pattern "third_party" match no issues
WARN [runner/exclusion_rules] Skipped 0 issues by rules: [Text: "cachedBytes", Path: "pagefile.go", Linters: "unused"]
WARN [runner/exclusion_rules] Skipped 0 issues by rules: [Path: "third_party", Linters: "gci, gofumpt"]
receiver/windowseventlogreceiver/factory_test.go:45:3: error-is-as: use assert.ErrorIs or assert.ErrorAs depending on the case (testifylint)
		assert.IsType(t, pipeline.ErrSignalNotSupported, err)
		^
make: *** [lint] Error 1
```

---------

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>