Add BoolGetter and BoolLikeGetter for IsBool
Introduces two new types, BoolGetter and BoolLikeGetter, as
prerequisites for the upcoming IsBool Converter feature.

BoolGetter is designed to retrieve a bool value directly and will
return a TypeError if the type doesn't match. It only accepts:

  1. Native bool
  2. pcommon.ValueTypeBool

BoolLikeGetter will attempt to convert the underlying value to a bool,
if possible, and return an error for incompatible types. It accepts
bool, int, int64, string, and float64, as well as corresponding
pcommon.ValueTypes. If the received pointer is nil, it will return nil.