[chore][ci] rename lychee options (#46158)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

Option name is `include_fragments` instead of `include-fragments`, and
`max-retries` to `max_retries`.

```sh
Error: OR] Error while loading config: Cannot load configuration file `.github/lychee.toml`: Failed to parse configuration file

Caused by:
    TOML parse error at line 1, column 1
      |
    1 | include-fragments = true
      | ^^^^^^^^^^^^^^^^^
    unknown field `include-fragments`, expected one of `files_from`, `verbose`, `no_progress`, `host_stats`, `extensions`, `default_extension`, `cache`, `max_cache_age`, `cache_exclude_status`, `dump`, `dump_inputs`, `archive`, `suggest`, `max_redirects`, `max_retries`, `min_tls`, `max_concurrency`, `host_concurrency`, `host_request_interval`, `threads`, `user_agent`, `insecure`, `scheme`, `offline`, `include`, `exclude`, `exclude_file`, `exclude_path`, `exclude_all_private`, `exclude_private`, `exclude_link_local`, `exclude_loopback`, `include_mail`, `remap`, `fallback_extensions`, `index_files`, `header`, `accept`, `include_fragments`, `timeout`, `retry_wait_time`, `method`, `base_url`, `root_dir`, `basic_auth`, `github_token`, `skip_missing`, `no_ignore`, `hidden`, `include_verbatim`, `glob_ignore_case`, `output`, `mode`, `format`, `generate`, `require_https`, `cookie_jar`, `include_wikilinks`, `preprocess`, `hosts`
```

See the CI error:
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/22106036346/job/63888927475?pr=46038

Options example:
https://github.com/lycheeverse/lychee/blob/lychee-v0.23.0/lychee.example.toml#L126

---------

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>