[chore][receiver/awscloudwatch] Fix linting (#45224)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

Fix the linting issue introduced by
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44468

```sh
Error: receiver/awscloudwatchreceiver/logs_test.go:366:4: slicescontains: Loop can be simplified using slices.Contains (modernize)
			for _, accountID := range input.AccountIdentifiers {
			^
```

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>