[chore][internal/aws/containerinsight] improve linting (#44892)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

This is part of the process to enable the
[modernize](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44199)
linter in CI and upgrade `golanglint` to the latest version.

There are no changes in the component behaviour.

```sh
Error: internal/aws/containerinsight/utils.go:38:13: G602: slice index out of range (gosec)
			if fields[i][k] == nil {
			         ^
Error: internal/aws/containerinsight/utils.go:41:23: G602: slice index out of range (gosec)
			if fv, ok := fields[i][k].(float64); ok {
```

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>