[chore][pkg/stanza] Use mdatagen for managing feature gates (#45533)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

The `mdatagen` recently added support for generating and documenting
feature gates.

In this PR, I'm updating all the existing feature gates with the
`mdatagen` ones.

Updated metadata.yaml with missing keys.

```sh
❯ mdatagen metadata.yaml
Error: failed loading opentelemetry-collector-contrib/pkg/stanza/metadata.yaml: missing type
missing stability
Error: failed loading opentelemetry-collector-contrib/pkg/stanza/metadata.yaml: missing type
missing stability
```

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>