[cmd/telemetrygen] ensure validate is called
Prior to this change, the Validate func wasn't being called resulting in wonky error messages
like the following:

```
2024-10-10T15:39:40.139-0700    INFO    logs/worker.go:49       stopping the exporter   {"worker": 0}
panic: runtime error: cannot convert slice with length 8 to array or pointer to array with length 16

goroutine 6 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen/internal/logs.worker.simulateLogs({0x140002404c4, 0x1, {0x100dd3152, 0xb}, 0x9, {0x100dccf6b, 0x4}, 0x0, 0x7fefffffffffffff, 0x140002404e0, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen/internal/logs/worker.go:70 +0xa34
created by github.com/open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen/internal/logs.Run in goroutine 1
```

With the validation in place, we now get a useful error message:

```
Error: TraceID must be a 32 character hex string, like: 'ae87dadd90e9935a4bc9660628efd569'
```

Signed-off-by: Alex Boten <223565+codeboten@users.noreply.github.com>