[chore] asapauthextension: fix tests under Go 1.24 (#41966)
#### Description

Under Go 1.24, use of RSA keys with fewer than 1024 bits leads to an
error. This causes the tests to fail like so:

```
=== RUN   TestRoundTripper
    extension_test.go:58:
                Error Trace:
/home/andrew/projects/opentelemetry-collector-contrib/extension/asapauthextension/extension_test.go:58
                Error:          Received unexpected error:
                                crypto/rsa: 512-bit keys are insecure
(see https://go.dev/pkg/crypto/rsa#hdr-Minimum_key_size)
                Test:           TestRoundTripper
--- FAIL: TestRoundTripper (0.00s)
```

Rather than using a hard-coded key pair, we can use httptest's internal
testing key pair which can be relied on to always be valid.

#### Link to tracking issue

https://github.com/open-telemetry/opentelemetry-collector/pull/13627

#### Testing

N/A

#### Documentation

N/A