[chore][receiver/namedpipereceiver] run make modernize (#44895)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

This is part of the process to enable the
[modernize](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44199)
linter in CI and upgrade `golanglint` to the latest version.

There are no changes in the component behaviour.

```sh
Error: receiver/namedpipereceiver/namedpipe_test.go:70:6: rangeint: for loop can be modernized using range over int (modernize)
	for i := 0; i < numLogs; i++ {
	    ^
make[2]: *** [../../Makefile.Common:282: lint] Error 1
make[1]: *** [Makefile:276: receiver/namedpipereceiver] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>