telemetrygen: Allow setting custom paths (#24551)
The current description for the flag is wrong.

```
❯ ../../open-telemetry/opentelemetry-collector-contrib/cmd/telemetrygen/telemetrygen metrics --otlp-endpoint example.com/v1/metrics  --otlp-http --otlp-insecure
2023-07-25T22:03:45.884+0200	INFO	metrics/metrics.go:56	starting HTTP exporter
Error: failed to obtain OTLP exporter: parse "http://example.com%2Fv1%2Fmetrics/v1/metrics": invalid URL escape "%2F"
```

I couldn't make it easily work with the existing flag because
`url.Parse(c.Endpoint)` puts everything in path, and u.Host is unset.
This is because url.Parse expects `http://` or `https://` which is set
through a different flag.

Signed-off-by: Goutham <gouthamve@gmail.com>
Co-authored-by: Pablo Baeyens <pbaeyens31+github@gmail.com>