[ci] pin prometheus-compliance tests to pre golang 1.25 requirement (#45351)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

The introduction of the following
[commit](https://github.com/prometheus/compliance/commit/3de836d255ffc98bbf7d58eb487b7662b496d047)
into the prometheus-compliance repository makes the go requirement
`1.25`, and all the `prometheus-compliance-tests` are now failing.

This PR pins the commit used to the one before requirement `1.25` to
unblock the CI.

~~I'll create an issue to remove this pin when we bump the collector
golang version to 1.25.~~ Issue created:
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/45353

Example of CI failure:
https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/20922584832/job/60111781774?pr=45346

```sh
Run go mod tidy
go: go.mod requires go >= 1.25.0 (running go 1.24.11; GOTOOLCHAIN=local)
Error: Process completed with exit code 1.
```

Signed-off-by: Paulo Dias <paulodias.gm@gmail.com>