exporters/prometheusremotewrite: Prevent duplicate samples by allowing an empty WAL (#44467)
#### Description
This PR prevents duplicate samples by allowing the WAL to be empty on
truncate.

Since the WAL is being truncated after every send it's likely the reader
and writer are in sync from an index perspective. Since WAL was not
allowed to be empty, the reader would always re-read previously
delivered samples causing duplicate data to be sent continuously.

Docs for the `AllowEmpty` setting in the WAL library,
```go
// AllowEmpty allows for a log to have all entries removed through the use
// of TruncateFront() or TruncateBack(). Otherwise without this option,
// at least one entry must always remain following a truncate operation.
// Default false
//
// Warning: using this option changes the behavior of the log in the
// following ways:
// - An empty log will always have the FirstIndex() be equal to
//   LastIndex()+1.
// - For a newly created log that has no entries, FirstIndex() and
//   LastIndex() return 1 and 0, respectively.
//   Without AllowEmpty, both return 0.
```

#### Link to tracking issue
Fixes #41785

#### Testing

I fixed the existing test that was intended to cover this type of
scenario so it could cover this. The test wasn't waiting for the data to
be received so the test was always passing even when data was not
received plus a few default config issues. After resolving those issues
+ updating the test to be a bit more strict it failed as expected since
we were constantly spamming the same payloads,
```
wal_test.go:252: 
        	Error Trace:	/Users/keckhart/src/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter/wal_test.go:253
        	            				/Users/keckhart/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.4.darwin-arm64/src/runtime/asm_arm64.s:1223
        	Error:      	Not equal: 
        	            	expected: 26661
        	            	actual  : 2
```

I also verified out of order writes were no longer received with the
collector config + prometheus setup in the linked issue.