[receiver/activedirectoryds] [docs] Update example in README (#37424)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

Update example in README to reflect map instead of bool that is
expected.

```
$ otelcol --version                                                                                                                          
otelcontribcol version 0.118.0-dev 

$ otelcol validate --config config.yaml
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'receivers': error reading configuration for "active_directory_ds": decoding failed due to the following error(s):

'metrics.active_directory.ds.replication.network.io' expected a map, got 'bool'
2025/01/22 18:33:20 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following
 error(s):

error decoding 'receivers': error reading configuration for "active_directory_ds": decoding failed due to the following error(s):

'metrics.active_directory.ds.replication.network.io' expected a map, got 'bool'


```

<!-- Issue number (e.g. #1234) or full URL to issue, if applicable. -->
#### Link to tracking issue
Fixes

<!--Describe what testing was performed and which tests were added.-->
#### Testing

<!--Describe the documentation added.-->
#### Documentation
Updated example used in README for this receiver to not throw errors. 

<!--Please delete paragraphs that you did not use before submitting.-->