[pkg/xk8stest] display collector pod events (#46306)
<!--Ex. Fixing a bug - Describe the bug and how this fixes the issue.
Ex. Adding a feature - Explain what this achieves.-->
#### Description

This change is meant to make debugging errors in k8s e2e tests a little
easier. When `WaitForCollectorToStart` times out, we now query and print
the pod events for any collector pod that isn't ready. So instead of
just a timeout message, you get the below output:

```
❯ go test -v --tags=e2e -run TestE2EConsulDetector -timeout 5m
=== RUN   TestE2EConsulDetector
    k8s_collector.go:70: waiting for collector pods to be ready
    k8s_collector.go:72: did not find collector pods
    k8s_collector.go:72: pod otelcol-756e59a6-6b5466b969-7lmpl is not running, current phase: Pending
    k8s_collector.go:72: pod otelcol-756e59a6-6b5466b969-7lmpl is not running, current phase: Pending
    k8s_collector.go:72: pod otelcol-756e59a6-6b5466b969-7lmpl is not running, current phase: Pending
    k8s_collector.go:72: pod otelcol-756e59a6-6b5466b969-7lmpl is not running, current phase: Pending
    k8s_collector.go:72: pod otelcol-756e59a6-6b5466b969-7lmpl is not running, current phase: Pending
    k8s_collector.go:72: pod otelcol-756e59a6-6b5466b969-7lmpl is not running, current phase: Pending
    k8s_collector.go:79: --- events for pod otelcol-756e59a6-6b5466b969-7lmpl (phase: Pending) ---
    k8s_collector.go:79:   Normal  Scheduled  default-scheduler  Successfully assigned default/otelcol-756e59a6-6b5466b969-7lmpl to e2e-test-control-plane
    k8s_collector.go:79:   Normal  Pulling  kubelet  Pulling image "hashicorp/consul:1.22.3-fake"
    k8s_collector.go:79:   Warning  Failed  kubelet  Failed to pull image "hashicorp/consul:1.22.3-fake": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/hashicorp/consul:1.22.3-fake": failed to resolve reference "docker.io/hashicorp/consul:1.22.3-fake": docker.io/hashicorp/consul:1.22.3-fake: not found
    k8s_collector.go:79:   Warning  Failed  kubelet  Error: ErrImagePull
    k8s_collector.go:79:   Normal  Pulled  kubelet  Container image "otelcontribcol:latest" already present on machine
    k8s_collector.go:79:   Normal  Created  kubelet  Created container: otelcol
    k8s_collector.go:79:   Normal  Started  kubelet  Started container otelcol
    k8s_collector.go:79:   Normal  BackOff  kubelet  Back-off pulling image "hashicorp/consul:1.22.3-fake"
    k8s_collector.go:79:   Warning  Failed  kubelet  Error: ImagePullBackOff
    k8s_collector.go:79:   Warning  BackOff  kubelet  Back-off restarting failed container otelcol in pod otelcol-756e59a6-6b5466b969-7lmpl_default(7a9d7066-bf7a-4582-babf-579927682223)
    k8s_collector.go:80: 
                Error Trace:    /Users/jjain/work/opentelemetry-collector-contrib/pkg/xk8stest/k8s_collector.go:80
                                                        /Users/jjain/work/opentelemetry-collector-contrib/pkg/xk8stest/k8s_collector.go:58
                                                        /Users/jjain/work/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/e2e_test.go:420
                Error:          collector pods were not ready
                Test:           TestE2EConsulDetector
                Messages:       timed out after 3m0s
--- FAIL: TestE2EConsulDetector (180.92s)
```

This is meant to make debugging errors in k8s e2e tests a little easier.

<!-- Issue number (e.g. #1234) or full URL to issue, if applicable. -->
#### Link to tracking issue
Fixes #46305

<!--Describe what testing was performed and which tests were added.-->
#### Testing
Tried running this on local with a failing e2e test. The output above is
from test run.

---------

Co-authored-by: Yang Song <songy23@users.noreply.github.com>